runtime: php81
env: standard

runtime_config:
  document_root: .

handlers:
  - url: /(.*\.(gif|png|jpg|css|js))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js)$
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  LOG_CHANNEL: stderr
  APP_LOG_PATH: /tmp/logs/laravel.log
  APP_KEY: base64:LrkhXSyIiwF8OYyTAe3UrVanuGvUuiDHcog6KlILvM0=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_STORE_PATH: /tmp/framework/cache/data


  DB_CONNECTION: mysql
  DB_HOST: 34.101.32.212
  DB_PORT: 3306
  DB_DATABASE: ecocrafters-api
  DB_USERNAME: root
  DB_PASSWORD: smkn7smd

  APP_NAME: EcoCrafters
  APP_ENV: production
  APP_DEBUG: true
  APP_URL: https://ecocrafters-api.et.r.appspot.com
  ASSET_URL: ""

  SESSION_DRIVER: cookie

  QUEUE_CONNECTION: sync

  MAIL_MAILER: smtp
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: 587
  MAIL_USERNAME: argifatur@gmail.com
  MAIL_PASSWORD: dttwlemrbcvrrzyh
  MAIL_ENCRYPTION: tls
  MAIL_FROM_ADDRESS: webdev@om.com
  MAIL_FROM_NAME: EcoCrafters

  PUSHER_APP_ID:
  PUSHER_APP_KEY:
  PUSHER_APP_SECRET:
  PUSHER_APP_CLUSTER: mt1

  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php
